services:
  backend_rds:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/prod_rds:${IMAGE_TAG}"
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend_redis:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/prod_redis:${IMAGE_TAG}"
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure